// Datos iniciales enriquecidos para la plataforma MTC - Rutas Ferroviarias y Zonas Turísticas
import { 
  TblEstacion, 
  TblZonaTuristica, 
  TblHorarioTren, 
  TblPronosticoClima, 
  TblPreferenciaTuristica,
  TblEstadoIntegracion 
} from '@/types/database';

export const INITIAL_PREFERENCIAS: TblPreferenciaTuristica[] = [
  {
    pre_id: 'pref_01',
    pre_codigo: 'naturaleza',
    pre_nombre: 'Naturaleza & Paisajes',
    pre_icono: 'Trees',
    pre_descripcion: 'Cascadas, flora nativa, montañas, orquídeas y vistas panorámicas andinas.',
    pre_color_badge: 'bg-emerald-100 text-emerald-800 border-emerald-300',
  },
  {
    pre_id: 'pref_02',
    pre_codigo: 'arqueologia',
    pre_nombre: 'Arqueología & Ruinas',
    pre_icono: 'Landmark',
    pre_descripcion: 'Complejos arqueológicos milenarios, andenerías, fortalezas y templos incas.',
    pre_color_badge: 'bg-amber-100 text-amber-800 border-amber-300',
  },
  {
    pre_id: 'pref_03',
    pre_codigo: 'historia',
    pre_nombre: 'Historia & Patrimonio',
    pre_icono: 'Compass',
    pre_descripcion: 'Centros históricos, templos coloniales, arquitectura virreinal y museos.',
    pre_color_badge: 'bg-blue-100 text-blue-800 border-blue-300',
  },
  {
    pre_id: 'pref_04',
    pre_codigo: 'gastronomia',
    pre_nombre: 'Gastronomía & Mercados',
    pre_icono: 'Utensils',
    pre_descripcion: 'Mercados tradicionales, platos típicos, café de altura y cocina cusqueña.',
    pre_color_badge: 'bg-orange-100 text-orange-800 border-orange-300',
  },
  {
    pre_id: 'pref_05',
    pre_codigo: 'fotografia',
    pre_nombre: 'Fotografía & Miradores',
    pre_icono: 'Camera',
    pre_descripcion: 'Puntos panorámicos estratégicos, puestas de sol y vistas instagrameables.',
    pre_color_badge: 'bg-purple-100 text-purple-800 border-purple-300',
  },
  {
    pre_id: 'pref_06',
    pre_codigo: 'aventura',
    pre_nombre: 'Aventura & Senderismo',
    pre_icono: 'Mountain',
    pre_descripcion: 'Senderos peatonales, escalinatas incas, caminos de herradura y reto físico.',
    pre_color_badge: 'bg-red-100 text-red-800 border-red-300',
  },
  {
    pre_id: 'pref_07',
    pre_codigo: 'cultura',
    pre_nombre: 'Cultura Viva & Artesanías',
    pre_icono: 'Sparkles',
    pre_descripcion: 'Talleres de artesanos, textilería andina tradicional y comunidades vivientes.',
    pre_color_badge: 'bg-pink-100 text-pink-800 border-pink-300',
  },
  {
    pre_id: 'pref_08',
    pre_codigo: 'descanso',
    pre_nombre: 'Descanso & Aguas Termales',
    pre_icono: 'HeartPulse',
    pre_descripcion: 'Baños termomedicinales, paseos tranquilos y relajación en la naturaleza.',
    pre_color_badge: 'bg-teal-100 text-teal-800 border-teal-300',
  },
];

export const INITIAL_ESTACIONES: TblEstacion[] = [
  {
    est_id: 'est_01',
    est_codigo: 'EST-CUS-SP',
    est_nombre: 'Estación San Pedro (Cusco)',
    est_ciudad: 'Cusco',
    est_departamento: 'Cusco',
    est_altitud_msnm: 3399,
    est_latitud: -13.5204,
    est_longitud: -71.9828,
    est_descripcion: 'Ubicada en el corazón histórico de Cusco, frente al célebre Mercado Central y a escasas cuadras de la Plaza de Armas.',
    est_servicios: ['Boletería PeruRail', 'Sala de espera VIP', 'Información turística iPerú', 'Custodia de equipaje', 'Cafetería andina', 'Wifi gratuito'],
    est_imagen_url: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=1200&q=80',
    est_telefono_contacto: '+51 (84) 581414',
  },
  {
    est_id: 'est_02',
    est_codigo: 'EST-CUS-POR',
    est_nombre: 'Estación Poroy (Cusco)',
    est_ciudad: 'Poroy',
    est_departamento: 'Cusco',
    est_altitud_msnm: 3499,
    est_latitud: -13.4912,
    est_longitud: -72.0465,
    est_descripcion: 'Punto de partida ideal en las afueras de la ciudad imperial de Cusco hacia el Valle Sagrado y Machu Picchu.',
    est_servicios: ['Boletería', 'Estacionamiento vigilado', 'Servicio de maleteros', 'Cafetería', 'Servicios higiénicos accesibles'],
    est_imagen_url: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80',
    est_telefono_contacto: '+51 (84) 581420',
  },
  {
    est_id: 'est_03',
    est_codigo: 'EST-VAL-OLL',
    est_nombre: 'Estación Ollantaytambo',
    est_ciudad: 'Ollantaytambo',
    est_departamento: 'Cusco (Valle Sagrado)',
    est_altitud_msnm: 2792,
    est_latitud: -13.2589,
    est_longitud: -72.2638,
    est_descripcion: 'Principal nodo ferroviario del Valle Sagrado con conexión directa diaria hacia Machu Picchu.',
    est_servicios: ['Boletería automatizada', 'Salas de embarque', 'Restaurantes', 'Módulo SENAMHI', 'Artesanías locales', 'Parqueo de bicicletas'],
    est_imagen_url: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=1200&q=80',
    est_telefono_contacto: '+51 (84) 581430',
  },
  {
    est_id: 'est_04',
    est_codigo: 'EST-MAC-AGU',
    est_nombre: 'Estación Machu Picchu Pueblo (Aguas Calientes)',
    est_ciudad: 'Machu Picchu Pueblo',
    est_departamento: 'Cusco',
    est_altitud_msnm: 2040,
    est_latitud: -13.1549,
    est_longitud: -72.5255,
    est_descripcion: 'Estación terminal a orillas del río Vilcanota, puerta de entrada peatonal y vehicular al Santuario Histórico de Machu Picchu.',
    est_servicios: ['Centro de atención al visitante', 'Boletería', 'Embarque preferencial', 'Asistencia médica', 'Oficina MTC / Dircetur'],
    est_imagen_url: 'https://images.unsplash.com/photo-1509299349698-dd22323b5963?auto=format&fit=crop&w=1200&q=80',
    est_telefono_contacto: '+51 (84) 581440',
  },
  {
    est_id: 'est_05',
    est_codigo: 'EST-VAL-URU',
    est_nombre: 'Estación Urubamba',
    est_ciudad: 'Urubamba',
    est_departamento: 'Cusco (Valle Sagrado)',
    est_altitud_msnm: 2870,
    est_latitud: -13.3056,
    est_longitud: -72.1158,
    est_descripcion: 'Estación rodeada de clima templado y valles fértiles, conectada con hoteles boutique y huertos orgánicos.',
    est_servicios: ['Boletería', 'Salón de espera', 'Jardín andino', 'Información turística', 'Café bar'],
    est_imagen_url: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=1200&q=80',
    est_telefono_contacto: '+51 (84) 581450',
  },
  {
    est_id: 'est_06',
    est_codigo: 'EST-PUN-TIT',
    est_nombre: 'Estación Puno (Lago Titicaca)',
    est_ciudad: 'Puno',
    est_departamento: 'Puno',
    est_altitud_msnm: 3827,
    est_latitud: -15.8364,
    est_longitud: -70.0219,
    est_descripcion: 'Estación histórica a orillas del lago navegable más alto del mundo, conectando el Altiplano con Cusco.',
    est_servicios: ['Boletería Titicaca Train', 'Sala de embarque folclórica', 'Oxígeno de cortesía', 'Custodia de equipaje'],
    est_imagen_url: 'https://images.unsplash.com/photo-1534008897995-27a23e859048?auto=format&fit=crop&w=1200&q=80',
    est_telefono_contacto: '+51 (51) 351041',
  },
];

export const INITIAL_ZONAS_TURISTICAS: TblZonaTuristica[] = [
  // --- Zonas desde Estación Machu Picchu Pueblo (est_04) ---
  {
    zon_id: 'zon_01',
    zon_estacion_id: 'est_04',
    zon_nombre: 'Baños Termomedicinales de Aguas Calientes',
    zon_categoria: 'descanso',
    zon_resumen_corto: 'Pozas naturales de aguas termales sulfurosas rodeadas de exuberante selva alta.',
    zon_descripcion: 'Ubicadas a poca distancia del centro del pueblo ascendiendo por una agradable alameda peatonal. Sus aguas brotan de fallas geológicas a temperaturas entre 38°C y 44°C, ideales para relajar músculos tras una jornada de caminata.',
    zon_distancia_metros: 850,
    zon_tiempo_caminata_min: 12,
    zon_tiempo_sugerido_visita_min: 90,
    zon_dificultad: 'Fácil',
    zon_desnivel_metros: 35,
    zon_puntos_interes: [
      'Alameda de los Artesanos',
      'Puente de piedra sobre el río Aguas Calientes',
      'Pozas termales al aire libre con vista a los farallones rocosos'
    ],
    zon_recomendaciones: [
      'Llevar traje de baño, toalla y sandalias antideslizantes',
      'Hidratarse con agua mineral antes y después de ingresar a las pozas',
      'Se alquilan casilleros en el establecimiento'
    ],
    zon_latitud: -13.1512,
    zon_longitud: -72.5218,
    zon_imagen_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 20,
    zon_horario_atencion: '05:00 - 20:00 (Lunes a Domingo)',
    zon_es_destacado: true,
  },
  {
    zon_id: 'zon_02',
    zon_estacion_id: 'est_04',
    zon_nombre: 'Jardines Ecológicos y Cataratas de Mandor',
    zon_categoria: 'naturaleza',
    zon_resumen_corto: 'Reserva natural con cascada cristalina, orquídeas nativas y aves endémicas.',
    zon_descripcion: 'Paseo ecológico bordeando la vía férrea y el río Vilcanota. Hogar del gallito de las rocas, colibríes y más de 200 especies de orquídeas autóctonas. Al final del sendero espera una imponente cascada de 30 metros.',
    zon_distancia_metros: 3800,
    zon_tiempo_caminata_min: 45,
    zon_tiempo_sugerido_visita_min: 120,
    zon_dificultad: 'Moderado',
    zon_desnivel_metros: 80,
    zon_puntos_interes: [
      'Sendero botánico de orquídeas y bromelias',
      'Mirador del cañón del Vilcanota',
      'Catarata de Mandor y poza de relajación',
      'Casona histórica de la familia Mandor'
    ],
    zon_recomendaciones: [
      'Usar repelente ecológico y bloqueador solar biodegradable',
      'Llevar calzado de caminata con buena tracción',
      'Llevar impermeable ligero para posibles lloviznas'
    ],
    zon_latitud: -13.1425,
    zon_longitud: -72.5482,
    zon_imagen_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 10,
    zon_horario_atencion: '06:30 - 16:30 (Lunes a Domingo)',
    zon_es_destacado: true,
  },
  {
    zon_id: 'zon_03',
    zon_estacion_id: 'est_04',
    zon_nombre: 'Museo de Sitio Manuel Chávez Ballón & Jardín Botánico',
    zon_categoria: 'arqueologia',
    zon_resumen_corto: 'Colección arqueológica de las excavaciones de Machu Picchu y sendero botánico.',
    zon_descripcion: 'Ubicado al pie de la montaña de Machu Picchu cruzando el Puente Ruinas. Exhibe piezas líticas, cerámicas, herramientas de metalurgia inca y paneles interactivos sobre la ingeniería incaica.',
    zon_distancia_metros: 1900,
    zon_tiempo_caminata_min: 25,
    zon_tiempo_sugerido_visita_min: 75,
    zon_dificultad: 'Fácil',
    zon_desnivel_metros: 40,
    zon_puntos_interes: [
      'Puente Ruinas sobre el río Urubamba',
      'Salas temáticas de arquitectura e ingeniería lítica inca',
      'Jardín botánico con flora endémica del Santuario'
    ],
    zon_recomendaciones: [
      'Presentar DNI o Pasaporte en la entrada',
      'Se puede combinar con la caminata hacia Mandor',
      'Acceso peatonal señalizado con paneles del MTC'
    ],
    zon_latitud: -13.1583,
    zon_longitud: -72.5369,
    zon_imagen_url: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 22,
    zon_horario_atencion: '09:00 - 16:00 (Lunes a Sábado)',
    zon_es_destacado: false,
  },
  {
    zon_id: 'zon_04',
    zon_estacion_id: 'est_04',
    zon_nombre: 'Mercado Artesanal & Paseo de Esculturas Líticas',
    zon_categoria: 'cultura',
    zon_resumen_corto: 'Galería peatonal abierta con más de 37 esculturas en piedra y textilería tradicional.',
    zon_descripcion: 'Justo a la salida de la estación ferroviaria se despliega este circuito peatonal repleto de artesanías finas, tejidos de alpaca y esculturas esculpidas en granito que representan deidades andinas.',
    zon_distancia_metros: 200,
    zon_tiempo_caminata_min: 3,
    zon_tiempo_sugerido_visita_min: 45,
    zon_dificultad: 'Fácil',
    zon_desnivel_metros: 5,
    zon_puntos_interes: [
      'Escultura del Cóndor Andino y la Pachamama',
      'Puestos de textilería tradicional y platería',
      'Cafeterías de especialidad con granos de Quillabamba'
    ],
    zon_recomendaciones: [
      'Ideal para recorrer mientras se espera la salida del tren',
      'Aceptan pagos con tarjeta y efectivo en soles'
    ],
    zon_latitud: -13.1542,
    zon_longitud: -72.5248,
    zon_imagen_url: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 0,
    zon_horario_atencion: '06:00 - 21:00 (Lunes a Domingo)',
    zon_es_destacado: false,
  },

  // --- Zonas desde Estación Ollantaytambo (est_03) ---
  {
    zon_id: 'zon_05',
    zon_estacion_id: 'est_03',
    zon_nombre: 'Fortaleza y Complejo Arqueológico de Ollantaytambo',
    zon_categoria: 'arqueologia',
    zon_resumen_corto: 'Colosal fortaleza militar, ceremonial y agrícola con el imponente Templo del Sol.',
    zon_descripcion: 'Una de las mayores joyas de la arquitectura incaica. Caminando desde la estación por las calles empedradas se llega a las imponentes terrazas megalíticas y al Templo del Sol, escenario de la gran victoria inca ante los conquistadores.',
    zon_distancia_metros: 650,
    zon_tiempo_caminata_min: 9,
    zon_tiempo_sugerido_visita_min: 120,
    zon_dificultad: 'Moderado',
    zon_desnivel_metros: 65,
    zon_puntos_interes: [
      'Andenería monumental de ascenso',
      'Templo de las Diez Ventanas',
      'Muro de los Seis Monolitos de Granito Rosado',
      'Baño de la Ñusta y fuentes hidráulicas ceremoniales'
    ],
    zon_recomendaciones: [
      'Requiere Boleto Turístico del Cusco (BTC)',
      'Llevar agua y sombrero de ala ancha',
      'El ascenso tiene escalinatas empinadas pero con descansos'
    ],
    zon_latitud: -13.2575,
    zon_longitud: -72.2655,
    zon_imagen_url: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 70,
    zon_horario_atencion: '07:00 - 17:30 (Lunes a Domingo)',
    zon_es_destacado: true,
  },
  {
    zon_id: 'zon_06',
    zon_estacion_id: 'est_03',
    zon_nombre: 'Colcas Sagradas de Pinkuylluna & Mirador',
    zon_categoria: 'aventura',
    zon_resumen_corto: 'Almacenes agrícolas incas suspendidos en el acantilado frente a la fortaleza.',
    zon_descripcion: 'Sendero peatonal de ascenso libre hacia los depósitos incas construidos en la ladera vertical del cerro Pinkuylluna. Ofrece una vista aérea inigualable del trazado urbano inca y de la fortaleza.',
    zon_distancia_metros: 950,
    zon_tiempo_caminata_min: 20,
    zon_tiempo_sugerido_visita_min: 60,
    zon_dificultad: 'Moderado',
    zon_desnivel_metros: 95,
    zon_puntos_interes: [
      'Almacenes incas de granos con sistema de ventilación natural',
      'Vista panorámica en 360° del Valle Sagrado',
      'Rostro esculpido del dios Tunupa en la roca'
    ],
    zon_recomendaciones: [
      'Ingreso libre y gratuito',
      'Subir con calzado con agarre, no apto para personas con vértigo severo',
      'Último ingreso recomendado a las 16:00'
    ],
    zon_latitud: -13.2558,
    zon_longitud: -72.2618,
    zon_imagen_url: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 0,
    zon_horario_atencion: '07:00 - 16:30 (Lunes a Domingo)',
    zon_es_destacado: true,
  },
  {
    zon_id: 'zon_07',
    zon_estacion_id: 'est_03',
    zon_nombre: 'Callejones y Pueblo Viviente Inca de Ollantaytambo',
    zon_categoria: 'historia',
    zon_resumen_corto: 'El único pueblo inca que conserva intacto su trazado urbanístico original desde el siglo XV.',
    zon_descripcion: 'Recorrido a pie por las "canchas" o manzanas incas originales, con canales de agua limpia corriendo por el centro de las calles empedradas y portadas de doble jamba aún habitadas por pobladores locales.',
    zon_distancia_metros: 400,
    zon_tiempo_caminata_min: 6,
    zon_tiempo_sugerido_visita_min: 60,
    zon_dificultad: 'Fácil',
    zon_desnivel_metros: 10,
    zon_puntos_interes: [
      'Plaza de Armas de Ollantaytambo',
      'Callejón de la Fortaleza y canales hidráulicos originales',
      'Picanterías y cafeterías tradicionales cusqueñas'
    ],
    zon_recomendaciones: [
      'Paseo muy accesible para todas las edades',
      'Excelente para tomar fotografías arquitectónicas',
      'Probar la tradicional chicha de jora o café orgánico'
    ],
    zon_latitud: -13.2582,
    zon_longitud: -72.2625,
    zon_imagen_url: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 0,
    zon_horario_atencion: 'Abierto 24 horas (Circuito público)',
    zon_es_destacado: false,
  },

  // --- Zonas desde Estación San Pedro (est_01) ---
  {
    zon_id: 'zon_08',
    zon_estacion_id: 'est_01',
    zon_nombre: 'Mercado Central de San Pedro',
    zon_categoria: 'gastronomia',
    zon_resumen_corto: 'Epicentro gastronómico y cultural más vibrante y colorido del Cusco.',
    zon_descripcion: 'Frente a la misma estación, diseñado por Gustave Eiffel en 1925. Encontrarás secciones de jugos naturales, panes tradicionales de Oropesa, quesos andinos, hierbas medicinales y comida típica.',
    zon_distancia_metros: 120,
    zon_tiempo_caminata_min: 2,
    zon_tiempo_sugerido_visita_min: 60,
    zon_dificultad: 'Fácil',
    zon_desnivel_metros: 0,
    zon_puntos_interes: [
      'Sección de jugos exóticos y frutas andinas',
      'Pasillo de panes chuta y queso paria',
      'Zona de artesanías y amuletos tradicionales (Pachamama)'
    ],
    zon_recomendaciones: [
      'Probar el caldo de gallina o lechón cusqueño',
      'Llevar efectivo para compras menores',
      'Cuidar pertenencias personales en horas punta'
    ],
    zon_latitud: -13.5212,
    zon_longitud: -71.9822,
    zon_imagen_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 0,
    zon_horario_atencion: '06:00 - 18:30 (Lunes a Domingo)',
    zon_es_destacado: true,
  },
  {
    zon_id: 'zon_09',
    zon_estacion_id: 'est_01',
    zon_nombre: 'Plaza de Armas, Basílica Catedral y Templo de la Compañía',
    zon_categoria: 'historia',
    zon_resumen_corto: 'Corazón monumental del Imperio Inca y la época virreinal del Perú.',
    zon_descripcion: 'Caminando por la histórica calle Santa Clara y Marqués se desemboca en la imponente Plaza Mayor del Cusco, flanqueada por la Catedral, el templo de la Compañía de Jesús y portales coloniales.',
    zon_distancia_metros: 750,
    zon_tiempo_caminata_min: 10,
    zon_tiempo_sugerido_visita_min: 90,
    zon_dificultad: 'Fácil',
    zon_desnivel_metros: 15,
    zon_puntos_interes: [
      'Arco de Santa Clara',
      'Basílica Catedral del Cusco y lienzos de la Escuela Cusqueña',
      'Templo de la Compañía de Jesús',
      'Pileta central con la estatua del Inca Pachacútec'
    ],
    zon_recomendaciones: [
      'Hermosa iluminación nocturna a partir de las 18:00',
      'Paseo 100% peatonal por el eje procesional'
    ],
    zon_latitud: -13.5168,
    zon_longitud: -71.9788,
    zon_imagen_url: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 40,
    zon_horario_atencion: '10:00 - 18:00 (Catedral)',
    zon_es_destacado: true,
  },
  {
    zon_id: 'zon_10',
    zon_estacion_id: 'est_01',
    zon_nombre: 'Calle Hatun Rumiyoc & Piedra de los Doce Ángulos',
    zon_categoria: 'arqueologia',
    zon_resumen_corto: 'Obra maestra de la cantería inca tallada con precisión milimétrica.',
    zon_descripcion: 'Continuando desde la Plaza de Armas por el callejón Hatun Rumiyoc, se encuentra este icónico muro inca que formó parte del palacio del inca Inca Roca, hoy Palacio Arzobispal.',
    zon_distancia_metros: 1100,
    zon_tiempo_caminata_min: 14,
    zon_tiempo_sugerido_visita_min: 30,
    zon_dificultad: 'Fácil',
    zon_desnivel_metros: 20,
    zon_puntos_interes: [
      'Piedra de los 12 Ángulos perfectamente encajada',
      'Muro megalítico del Palacio de Inca Roca',
      'Paso hacia el tradicional barrio de San Blas'
    ],
    zon_recomendaciones: [
      'No tocar la superficie lítica para preservar el patrimonio',
      'Visita libre en cualquier horario del día'
    ],
    zon_latitud: -13.5159,
    zon_longitud: -71.9763,
    zon_imagen_url: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 0,
    zon_horario_atencion: 'Abierto 24 horas',
    zon_es_destacado: false,
  },

  // --- Zonas desde Estación Poroy (est_02) ---
  {
    zon_id: 'zon_11',
    zon_estacion_id: 'est_02',
    zon_nombre: 'Mirador Paisajístico del Valle de Poroy & Bosque Nativo',
    zon_categoria: 'fotografia',
    zon_resumen_corto: 'Vista panorámica de las colinas andinas y los campos de cultivo de maíz.',
    zon_descripcion: 'Sendero campestre que asciende suavemente desde la estación hasta un mirador natural rodeado de eucaliptos y quenuales, ideal para disfrutar del aire puro antes de abordar el tren.',
    zon_distancia_metros: 600,
    zon_tiempo_caminata_min: 9,
    zon_tiempo_sugerido_visita_min: 40,
    zon_dificultad: 'Fácil',
    zon_desnivel_metros: 30,
    zon_puntos_interes: [
      'Mirador del ferrocarril sur-oriente',
      'Bosque de queñuales y flora altoandina',
      'Puntos de descanso con bancas rústicas'
    ],
    zon_recomendaciones: [
      'Llevar abrigo ligero debido al viento matutino',
      'Caminar con tiempo holgado antes del chequeo de boletos'
    ],
    zon_latitud: -13.4935,
    zon_longitud: -72.0482,
    zon_imagen_url: 'https://images.unsplash.com/photo-1509299349698-dd22323b5963?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 0,
    zon_horario_atencion: 'Abierto en horario diurno',
    zon_es_destacado: false,
  },

  // --- Zonas desde Estación Urubamba (est_05) ---
  {
    zon_id: 'zon_12',
    zon_estacion_id: 'est_05',
    zon_nombre: 'Sendero Ribereño del Río Vilcanota & Taller Cerámico Seminario',
    zon_categoria: 'cultura',
    zon_resumen_corto: 'Paseo sombreado junto al río y visita a la prestigiosa cerámica de estilo precolombino.',
    zon_descripcion: 'Tranquila caminata bajo árboles nativos que conecta la estación de tren con la plaza principal de Urubamba y el afamado taller de Pablo Seminario, referente del arte cerámico contemporáneo del Perú.',
    zon_distancia_metros: 750,
    zon_tiempo_caminata_min: 10,
    zon_tiempo_sugerido_visita_min: 60,
    zon_dificultad: 'Fácil',
    zon_desnivel_metros: 10,
    zon_puntos_interes: [
      'Paseo peatonal ribereño del Vilcanota',
      'Exposición y hornos del Taller Seminario',
      'Plaza de Armas y Templo San Pedro de Urubamba'
    ],
    zon_recomendaciones: [
      'El taller ofrece demostraciones en vivo gratuitas',
      'Clima cálido durante todo el año'
    ],
    zon_latitud: -13.3032,
    zon_longitud: -72.1190,
    zon_imagen_url: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 0,
    zon_horario_atencion: '08:00 - 18:00 (Lunes a Sábado)',
    zon_es_destacado: false,
  },

  // --- Zonas desde Estación Puno (est_06) ---
  {
    zon_id: 'zon_13',
    zon_estacion_id: 'est_06',
    zon_nombre: 'Muelle Turístico del Lago Titicaca & Malecón Ecoturístico',
    zon_categoria: 'naturaleza',
    zon_resumen_corto: 'Malecón peatonal con vista panorámica a la bahía del lago navegable más alto del mundo.',
    zon_descripcion: 'Saliendo de la estación ferroviaria de Puno, a tan solo 4 minutos a pie se extiende el muelle turístico donde zarpan las lanchas hacia las islas flotantes de los Uros, con feria de artesanías y miradores lacustres.',
    zon_distancia_metros: 350,
    zon_tiempo_caminata_min: 5,
    zon_tiempo_sugerido_visita_min: 75,
    zon_dificultad: 'Fácil',
    zon_desnivel_metros: 5,
    zon_puntos_interes: [
      'Faro monumental de la bahía de Puno',
      'Embarcadero tradicional de totora',
      'Artesanías en lana de alpaca y totora trenzada'
    ],
    zon_recomendaciones: [
      'Llevar cortaviento y abrigo térmico por el frío altiplánico',
      'Excelente punto para fotografiar aves acuáticas como el zambullidor del Titicaca'
    ],
    zon_latitud: -13.1550, // Puno reference in map
    zon_longitud: -72.5250,
    zon_imagen_url: 'https://images.unsplash.com/photo-1534008897995-27a23e859048?auto=format&fit=crop&w=1200&q=80',
    zon_precio_entrada_pen: 0,
    zon_horario_atencion: '06:00 - 19:00 (Lunes a Domingo)',
    zon_es_destacado: true,
  }
];

export const INITIAL_HORARIOS_TREN: TblHorarioTren[] = [
  // --- De Ollantaytambo a Machu Picchu ---
  {
    hor_id: 'hor_01',
    hor_codigo_tren: 'EXP-61',
    hor_estacion_origen_id: 'est_03',
    hor_estacion_destino_id: 'est_04',
    hor_servicio_tipo: 'Expedition',
    hor_hora_salida: '06:10',
    hor_hora_llegada: '07:40',
    hor_duracion_min: 90,
    hor_tarifa_regular_pen: 120,
    hor_tarifa_turista_usd: 54,
    hor_dias_operacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    hor_asientos_disponibles: 42,
    hor_incluye_refrigerio: false,
  },
  {
    hor_id: 'hor_02',
    hor_codigo_tren: 'VIS-31',
    hor_estacion_origen_id: 'est_03',
    hor_estacion_destino_id: 'est_04',
    hor_servicio_tipo: 'Vistadome',
    hor_hora_salida: '07:05',
    hor_hora_llegada: '08:27',
    hor_duracion_min: 82,
    hor_tarifa_regular_pen: 190,
    hor_tarifa_turista_usd: 85,
    hor_dias_operacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    hor_asientos_disponibles: 28,
    hor_incluye_refrigerio: true,
  },
  {
    hor_id: 'hor_03',
    hor_codigo_tren: 'VOB-501',
    hor_estacion_origen_id: 'est_03',
    hor_estacion_destino_id: 'est_04',
    hor_servicio_tipo: 'Vistadome Observatory',
    hor_hora_salida: '08:53',
    hor_hora_llegada: '10:29',
    hor_duracion_min: 96,
    hor_tarifa_regular_pen: 245,
    hor_tarifa_turista_usd: 110,
    hor_dias_operacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    hor_asientos_disponibles: 18,
    hor_incluye_refrigerio: true,
  },
  {
    hor_id: 'hor_04',
    hor_codigo_tren: 'LOC-21',
    hor_estacion_origen_id: 'est_03',
    hor_estacion_destino_id: 'est_04',
    hor_servicio_tipo: 'Tren Local',
    hor_hora_salida: '05:00',
    hor_hora_llegada: '06:45',
    hor_duracion_min: 105,
    hor_tarifa_regular_pen: 12,
    hor_tarifa_turista_usd: 5,
    hor_dias_operacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    hor_asientos_disponibles: 90,
    hor_incluye_refrigerio: false,
  },

  // --- De Machu Picchu a Ollantaytambo (Retornos) ---
  {
    hor_id: 'hor_05',
    hor_codigo_tren: 'EXP-64',
    hor_estacion_origen_id: 'est_04',
    hor_estacion_destino_id: 'est_03',
    hor_servicio_tipo: 'Expedition',
    hor_hora_salida: '15:20',
    hor_hora_llegada: '17:08',
    hor_duracion_min: 108,
    hor_tarifa_regular_pen: 120,
    hor_tarifa_turista_usd: 54,
    hor_dias_operacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    hor_asientos_disponibles: 36,
    hor_incluye_refrigerio: false,
  },
  {
    hor_id: 'hor_06',
    hor_codigo_tren: 'VIS-32',
    hor_estacion_origen_id: 'est_04',
    hor_estacion_destino_id: 'est_03',
    hor_servicio_tipo: 'Vistadome',
    hor_hora_salida: '16:22',
    hor_hora_llegada: '18:10',
    hor_duracion_min: 108,
    hor_tarifa_regular_pen: 190,
    hor_tarifa_turista_usd: 85,
    hor_dias_operacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    hor_asientos_disponibles: 22,
    hor_incluye_refrigerio: true,
  },
  {
    hor_id: 'hor_07',
    hor_codigo_tren: 'VOB-504',
    hor_estacion_origen_id: 'est_04',
    hor_estacion_destino_id: 'est_03',
    hor_servicio_tipo: 'Vistadome Observatory',
    hor_hora_salida: '17:23',
    hor_hora_llegada: '19:02',
    hor_duracion_min: 99,
    hor_tarifa_regular_pen: 245,
    hor_tarifa_turista_usd: 110,
    hor_dias_operacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    hor_asientos_disponibles: 15,
    hor_incluye_refrigerio: true,
  },

  // --- De Poroy / Cusco a Machu Picchu ---
  {
    hor_id: 'hor_08',
    hor_codigo_tren: 'VIS-33',
    hor_estacion_origen_id: 'est_02',
    hor_estacion_destino_id: 'est_04',
    hor_servicio_tipo: 'Vistadome',
    hor_hora_salida: '07:35',
    hor_hora_llegada: '10:52',
    hor_duracion_min: 197,
    hor_tarifa_regular_pen: 260,
    hor_tarifa_turista_usd: 115,
    hor_dias_operacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    hor_asientos_disponibles: 32,
    hor_incluye_refrigerio: true,
  },
  {
    hor_id: 'hor_09',
    hor_codigo_tren: 'HIR-01',
    hor_estacion_origen_id: 'est_02',
    hor_estacion_destino_id: 'est_04',
    hor_servicio_tipo: 'Hiram Bingham',
    hor_hora_salida: '09:05',
    hor_hora_llegada: '12:24',
    hor_duracion_min: 199,
    hor_tarifa_regular_pen: 1250,
    hor_tarifa_turista_usd: 520,
    hor_dias_operacion: ['Lunes', 'Miércoles', 'Viernes', 'Sábado'],
    hor_asientos_disponibles: 12,
    hor_incluye_refrigerio: true,
  },

  // --- De San Pedro Cusco a Ollantaytambo / Machu Picchu ---
  {
    hor_id: 'hor_10',
    hor_codigo_tren: 'EXP-21',
    hor_estacion_origen_id: 'est_01',
    hor_estacion_destino_id: 'est_04',
    hor_servicio_tipo: 'Expedition',
    hor_hora_salida: '06:40',
    hor_hora_llegada: '10:15',
    hor_duracion_min: 215,
    hor_tarifa_regular_pen: 210,
    hor_tarifa_turista_usd: 90,
    hor_dias_operacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    hor_asientos_disponibles: 40,
    hor_incluye_refrigerio: false,
  }
];

export const INITIAL_PRONOSTICOS_CLIMA: Record<string, TblPronosticoClima> = {
  est_01: {
    cli_id: 'cli_cus_01',
    cli_estacion_id: 'est_01',
    cli_fecha: '2026-08-30',
    cli_temp_min_c: 5,
    cli_temp_max_c: 21,
    cli_temp_actual_c: 17,
    cli_condicion_cielo: 'Despejado',
    cli_prob_lluvia_pct: 10,
    cli_humedad_pct: 45,
    cli_viento_kmh: 12,
    cli_indice_uv: 11,
    cli_alerta_meteorologica: {
      nivel: 'Amarillo',
      mensaje: 'Radiación UV extrema en horas del mediodía (11:00 a 14:00).',
      recomendacion: 'Usar bloqueador solar FPS 50+, lentes con protección UV y sombrero.',
    },
    cli_recomendacion_ropa: ['Casaca cortaviento', 'Gorro/sombrero para sol', 'Ropa en capas', 'Zapatillas de paseo'],
    cli_fuente_senamhi: 'SENAMHI - Dirección Zonal 12 Cusco',
    cli_fecha_actualizacion: '2026-08-29 14:30:00 (Actualización Automática Diaria)',
  },
  est_02: {
    cli_id: 'cli_por_02',
    cli_estacion_id: 'est_02',
    cli_fecha: '2026-08-30',
    cli_temp_min_c: 4,
    cli_temp_max_c: 19,
    cli_temp_actual_c: 16,
    cli_condicion_cielo: 'Parcialmente Nublado',
    cli_prob_lluvia_pct: 15,
    cli_humedad_pct: 50,
    cli_viento_kmh: 15,
    cli_indice_uv: 10,
    cli_alerta_meteorologica: {
      nivel: 'Verde',
      mensaje: 'Condiciones meteorológicas estables y óptimas para caminatas.',
      recomendacion: 'Hidratarse constantemente por la altitud de 3,499 msnm.',
    },
    cli_recomendacion_ropa: ['Abrigo térmico matutino', 'Lentes de sol', 'Calzado cómodo'],
    cli_fuente_senamhi: 'SENAMHI - Estación Agrometeorológica Poroy',
    cli_fecha_actualizacion: '2026-08-29 14:30:00 (Actualización Automática Diaria)',
  },
  est_03: {
    cli_id: 'cli_oll_03',
    cli_estacion_id: 'est_03',
    cli_fecha: '2026-08-30',
    cli_temp_min_c: 8,
    cli_temp_max_c: 24,
    cli_temp_actual_c: 22,
    cli_condicion_cielo: 'Despejado',
    cli_prob_lluvia_pct: 5,
    cli_humedad_pct: 40,
    cli_viento_kmh: 8,
    cli_indice_uv: 12,
    cli_alerta_meteorologica: {
      nivel: 'Amarillo',
      mensaje: 'Índice de radiación solar muy alto. Viento fresco vespertino en el valle.',
      recomendacion: 'Recomendable iniciar recorridos peatonales antes de las 10:00 o después de las 14:30.',
    },
    cli_recomendacion_ropa: ['Polo de algodón transpirable', 'Pantalón de trekking desmontable', 'Gafas de sol', 'Botella de agua'],
    cli_fuente_senamhi: 'SENAMHI - Estación Meteorológica Ollantaytambo',
    cli_fecha_actualizacion: '2026-08-29 14:30:00 (Actualización Automática Diaria)',
  },
  est_04: {
    cli_id: 'cli_mac_04',
    cli_estacion_id: 'est_04',
    cli_fecha: '2026-08-30',
    cli_temp_min_c: 12,
    cli_temp_max_c: 26,
    cli_temp_actual_c: 23,
    cli_condicion_cielo: 'Parcialmente Nublado',
    cli_prob_lluvia_pct: 25,
    cli_humedad_pct: 78,
    cli_viento_kmh: 6,
    cli_indice_uv: 9,
    cli_alerta_meteorologica: {
      nivel: 'Verde',
      mensaje: 'Clima cálido y húmedo de ceja de selva. Probabilidad de neblina matutina en cumbres.',
      recomendacion: 'Llevar poncho impermeable liviano y repelente de insectos.',
    },
    cli_recomendacion_ropa: ['Impermeable o poncho para lluvia', 'Repelente para mosquitos', 'Zapatos de trekking impermeables', 'Ropa fresca'],
    cli_fuente_senamhi: 'SENAMHI - Estación Machu Picchu Pueblo',
    cli_fecha_actualizacion: '2026-08-29 14:30:00 (Actualización Automática Diaria)',
  },
  est_05: {
    cli_id: 'cli_uru_05',
    cli_estacion_id: 'est_05',
    cli_fecha: '2026-08-30',
    cli_temp_min_c: 7,
    cli_temp_max_c: 23,
    cli_temp_actual_c: 20,
    cli_condicion_cielo: 'Despejado',
    cli_prob_lluvia_pct: 8,
    cli_humedad_pct: 42,
    cli_viento_kmh: 10,
    cli_indice_uv: 11,
    cli_alerta_meteorologica: {
      nivel: 'Verde',
      mensaje: 'Excelente visibilidad y tiempo cálido templado.',
      recomendacion: 'Ideal para paseos ribereños a pie.',
    },
    cli_recomendacion_ropa: ['Ropa cómoda', 'Protector solar', 'Sombrero'],
    cli_fuente_senamhi: 'SENAMHI - Estación Urubamba',
    cli_fecha_actualizacion: '2026-08-29 14:30:00 (Actualización Automática Diaria)',
  },
  est_06: {
    cli_id: 'cli_pun_06',
    cli_estacion_id: 'est_06',
    cli_fecha: '2026-08-30',
    cli_temp_min_c: -1,
    cli_temp_max_c: 17,
    cli_temp_actual_c: 14,
    cli_condicion_cielo: 'Despejado',
    cli_prob_lluvia_pct: 5,
    cli_humedad_pct: 35,
    cli_viento_kmh: 18,
    cli_indice_uv: 13,
    cli_alerta_meteorologica: {
      nivel: 'Amarillo',
      mensaje: 'Descenso térmico nocturno y heladas meteorológicas en madrugada.',
      recomendacion: 'Vestimenta térmica gruesa al atardecer y anochecer.',
    },
    cli_recomendacion_ropa: ['Casaca de plumas o polar grueso', 'Guantes y chullo andino', 'Protector solar labial y facial'],
    cli_fuente_senamhi: 'SENAMHI - Dirección Zonal 13 Puno',
    cli_fecha_actualizacion: '2026-08-29 14:30:00 (Actualización Automática Diaria)',
  }
};

export const INITIAL_INTEGRACIONES: TblEstadoIntegracion[] = [
  {
    int_fuente: 'SENAMHI',
    int_estado: 'Sincronizado',
    int_ultima_sincronizacion: 'Hoy a las 06:00 AM (Actualización Diaria)',
    int_total_registros: 6,
    int_latencia_ms: 180,
    int_version_api: 'v2.4 - Red de Estaciones Meteorológicas Automáticas (EMA)',
    int_detalles: 'Flujo periódico de datos climáticos, radiación UV, temperaturas y alertas por estación.'
  },
  {
    int_fuente: 'PeruRail',
    int_estado: 'Sincronizado',
    int_ultima_sincronizacion: 'Hoy a las 05:30 AM (Actualización Diaria)',
    int_total_registros: 10,
    int_latencia_ms: 220,
    int_version_api: 'v3.1 - Sistema Central de Logística y Tarifario Ferroviario',
    int_detalles: 'Horarios de tránsito, frecuencias, disponibilidades y tarifas oficiales en PEN y USD.'
  },
  {
    int_fuente: 'Travel Group Perú',
    int_estado: 'Conectado',
    int_ultima_sincronizacion: 'Hoy a las 11:15 AM (Gestión en Línea)',
    int_total_registros: 13,
    int_latencia_ms: 95,
    int_version_api: 'v1.8 - Catálogo Turístico Georreferenciado Peatonal',
    int_detalles: 'Levantamiento y actualización de zonas turísticas a pie vinculadas a estaciones.'
  }
];
